import { RGBA } from "@opentui/core"
import path from "path"

export const icons = {
  user: "",
  think: "",
  assistant: "",
  bash: "",
  edit: "",
  glob: "",
  grep: "",
  memoryList: "󰒍",
  memorySearch: "󰍉",
  read: "󰈙",
  skill: "󰒓",
  task: "",
  todoWrite: "",
  write: "",
  debug: "",
} as const

const files = {
  dockerfile: "󰡨",
  "docker-compose.yml": "󰡨",
  "docker-compose.yaml": "󰡨",
  makefile: "",
  gnumakefile: "",
  "package.json": "",
  "package-lock.json": "",
  "bun.lockb": "",
  "bun.lock": "",
  "readme.md": "󰂺",
  readme: "󰂺",
  license: "",
  "license.md": "",
  ".gitignore": "",
  ".gitattributes": "",
  ".gitconfig": "",
  ".eslintrc": "",
  ".eslintignore": "",
  "eslint.config.js": "",
  ".prettierrc": "",
  ".prettierignore": "",
  "prettier.config.js": "",
  "tsconfig.json": "",
  "jsconfig.json": "",
  "vite.config.js": "",
  "vite.config.ts": "",
  "vitest.config.js": "",
  "vitest.config.ts": "",
  "next.config.js": "",
  "next.config.ts": "",
  "nuxt.config.js": "󱄆",
  "nuxt.config.ts": "󱄆",
  "tailwind.config.js": "󱏿",
  "tailwind.config.ts": "󱏿",
  "svelte.config.js": "",
  "webpack.config.js": "󰜫",
  ".env": "",
  "composer.json": "",
  "composer.lock": "",
  "go.mod": "",
  "go.sum": "",
  "cargo.toml": "",
  "cargo.lock": "",
  gemfile: "",
  "gemfile.lock": "",
  rakefile: "",
  "pom.xml": "",
  "build.gradle": "",
  "settings.gradle": "",
  ".zshrc": "",
  ".bashrc": "",
  ".bash_profile": "",
  ".vimrc": "",
  ".gvimrc": "",
  ".tmux.conf": "",
  ".nanorc": "",
  ".nvmrc": "",
  ".npmrc": "",
  ".npmignore": "",
  procfile: "",
  "cmakelists.txt": "",
  ".editorconfig": "",
  ".dockerignore": "󰡨",
  ".babelrc": "",
  "robots.txt": "󰚩",
}

const exts = {
  abap: "",
  bat: "",
  bib: "󱉟",
  bibtex: "󱉟",
  c: "",
  clj: "",
  cljs: "",
  cljc: "",
  edn: "",
  coffee: "",
  coffeescript: "",
  cpp: "",
  cxx: "",
  cc: "",
  "c++": "",
  cs: "󰌛",
  csharp: "󰌛",
  css: "",
  d: "",
  dart: "",
  dockerfile: "󰡨",
  ex: "",
  exs: "",
  elixir: "",
  erl: "",
  erlang: "",
  hrl: "",
  fs: "",
  fsi: "",
  fsx: "",
  fsscript: "",
  fsharp: "",
  gleam: "",
  go: "",
  groovy: "",
  gradle: "",
  hbs: "",
  handlebars: "",
  hs: "",
  haskell: "",
  lhs: "",
  htm: "",
  html: "",
  ini: "",
  java: "",
  jar: "",
  js: "",
  javascript: "",
  kt: "",
  kts: "",
  kotlin: "",
  json: "",
  json5: "",
  jsonc: "",
  less: "",
  lua: "",
  luau: "",
  md: "",
  markdown: "",
  mdx: "",
  m: "",
  mm: "",
  ml: "",
  mli: "",
  ocaml: "",
  pas: "󰏚",
  pascal: "󰏚",
  pl: "",
  pm: "",
  perl: "",
  php: "",
  ps1: "󰨊",
  psm1: "󰨊",
  psd1: "󰨊",
  powershell: "󰨊",
  py: "",
  pyc: "",
  pyd: "",
  pyi: "",
  pyo: "",
  python: "",
  r: "󰟔",
  rake: "",
  rakefile: "",
  rb: "",
  ruby: "",
  gemspec: "",
  ru: "",
  erb: "",
  rs: "",
  rust: "",
  rlib: "",
  sass: "",
  scss: "",
  scala: "",
  sc: "",
  shaderlab: "",
  sh: "",
  bash: "",
  zsh: "",
  ksh: "",
  fish: "",
  shellscript: "",
  sql: "",
  sqlite: "",
  sqlite3: "",
  swift: "",
  svelte: "",
  svx: "",
  tf: "",
  terraform: "",
  tfvars: "",
  toml: "",
  ts: "",
  typescript: "",
  mts: "",
  cts: "",
  tsx: "",
  typst: "󰪩",
  typ: "󰪩",
  vue: "",
  xml: "󰗿",
  xsl: "󰗿",
  yaml: "",
  yml: "",
  zig: "",
  zon: "",
  jsx: "",
  javascriptreact: "",
  typescriptreact: "",
  objectivec: "",
  objectivecpp: "",
  julia: "",
  jl: "",
  diff: "",
  patch: "",
  tex: "",
  latex: "",
  nix: "",
  hcl: "󱁢",
  astro: "",
  prisma: "",
  graphql: "",
  gql: "",
  dockerignore: "󰡨",
  ipynb: "",
  npmignore: "",
}

const langs = {
  astro: "",
  biome: "",
  deno: "",
  dockerfile: "󰡨",
  eslint: "",
  gopls: "",
  graphql: "",
  html: "",
  javascript: "",
  js: "",
  json: "",
  jsx: "",
  lua: "",
  markdown: "",
  mdx: "",
  node: "",
  nodejs: "",
  npm: "",
  pnpm: "",
  bun: "",
  prisma: "",
  python: "",
  rust: "",
  rustanalyzer: "",
  sql: "",
  stylelint: "",
  svelte: "",
  tailwindcss: "󱏿",
  terraform: "",
  typescript: "",
  ts: "",
  tsx: "",
  vue: "",
  vls: "",
  yaml: "",
  yml: "",
  c: "",
  cpp: "",
  csharp: "󰌛",
  java: "",
  jdtls: "",
  kotlin: "",
  swift: "",
  sourcekit: "",
  dart: "",
  flutter: "",
  zig: "",
  zls: "",
  ruby: "",
  solargraph: "",
  php: "",
  intelephense: "",
  perl: "",
  haskell: "",
  hls: "",
  elixir: "",
  erlang: "",
  clojure: "",
  ocaml: "",
  ocamllsp: "",
  fsharp: "",
  fsac: "",
  gleam: "",
  shellscript: "",
  bash: "",
  bashls: "",
  powershell: "󰨊",
  pwsh: "󰨊",
  nix: "",
  nil: "",
  typst: "󰪩",
  tinymist: "󰪩",
  latex: "",
  texlab: "",
  julia: "",
  julials: "",
  scala: "",
  metals: "",
  groovy: "",
  handlebars: "",
  diff: "",
  ini: "",
  xml: "󰗿",
  css: "",
  sass: "",
  scss: "",
  less: "",
  postcss: "",
  objectivec: "",
  objectivecpp: "",
  clangd: "",
  pascal: "󰏚",
  jade: "",
  pug: "",
  terraformvars: "",
}

const servers = {
  typescript: "",
  eslint: "",
  graphql: "",
  stylelint: "",
  biome: "",
  gopls: "",
  rustanalyzer: "",
  vls: "",
  jdtls: "",
  kotlin: "",
  sourcekit: "",
  dart: "",
  zls: "",
  solargraph: "",
  intelephense: "",
  hls: "",
  elixirls: "",
  erlangls: "",
  clojurelsp: "",
  ocamllsp: "",
  fsac: "",
  bashls: "",
  powershelleditor: "󰨊",
  nil: "",
  tinymist: "󰪩",
  texlab: "",
  julials: "",
  metals: "",
  clangd: "",
}

const c = (hex: string) => RGBA.fromHex(hex)

const fileTones = {
  dockerfile: c("#458EE6"),
  "docker-compose.yml": c("#458EE6"),
  "docker-compose.yaml": c("#458EE6"),
  makefile: c("#6D8086"),
  gnumakefile: c("#6D8086"),
  "package.json": c("#E8274B"),
  "package-lock.json": c("#7A0D21"),
  "bun.lockb": c("#EADCD1"),
  "bun.lock": c("#EADCD1"),
  "readme.md": c("#EDEDED"),
  readme: c("#EDEDED"),
  license: c("#D0BF41"),
  "license.md": c("#D0BF41"),
  ".gitignore": c("#F54D27"),
  ".gitattributes": c("#F54D27"),
  ".gitconfig": c("#F54D27"),
  ".eslintrc": c("#4B32C3"),
  ".eslintignore": c("#4B32C3"),
  "eslint.config.js": c("#4B32C3"),
  ".prettierrc": c("#4285F4"),
  ".prettierignore": c("#4285F4"),
  "prettier.config.js": c("#4285F4"),
  tsconfig: c("#519ABA"),
  "tsconfig.json": c("#519ABA"),
  jsconfig: c("#CBCB41"),
  "jsconfig.json": c("#CBCB41"),
  "vite.config.js": c("#FFA800"),
  "vite.config.ts": c("#FFA800"),
  "vitest.config.js": c("#739B1B"),
  "vitest.config.ts": c("#739B1B"),
  "next.config.js": c("#FFFFFF"),
  "next.config.ts": c("#FFFFFF"),
  "nuxt.config.js": c("#00C58E"),
  "nuxt.config.ts": c("#00C58E"),
  "tailwind.config.js": c("#20C2E3"),
  "tailwind.config.ts": c("#20C2E3"),
  "svelte.config.js": c("#FF3E00"),
  "webpack.config.js": c("#519ABA"),
  ".env": c("#FAF743"),
  "composer.json": c("#A074C4"),
  "composer.lock": c("#A074C4"),
  "go.mod": c("#00ADD8"),
  "go.sum": c("#00ADD8"),
  "cargo.toml": c("#DEA584"),
  "cargo.lock": c("#DEA584"),
  gemfile: c("#701516"),
  "gemfile.lock": c("#701516"),
  rakefile: c("#701516"),
  "pom.xml": c("#7A0D21"),
  "build.gradle": c("#005F87"),
  "settings.gradle": c("#005F87"),
  ".zshrc": c("#89E051"),
  ".bashrc": c("#89E051"),
  ".bash_profile": c("#89E051"),
  ".vimrc": c("#019833"),
  ".gvimrc": c("#019833"),
  ".tmux.conf": c("#14BA19"),
  ".nanorc": c("#440077"),
  ".nvmrc": c("#5FA04E"),
  ".npmrc": c("#E8274B"),
  ".npmignore": c("#E8274B"),
  procfile: c("#A074C4"),
  "cmakelists.txt": c("#DCE3EB"),
  ".editorconfig": c("#FFF2F2"),
  ".dockerignore": c("#458EE6"),
  ".babelrc": c("#CBCB41"),
  "robots.txt": c("#5D7096"),
}

const extTones = {
  bat: c("#C1F12E"),
  c: c("#599EFF"),
  clj: c("#8DC149"),
  cljs: c("#519ABA"),
  cljc: c("#8DC149"),
  edn: c("#519ABA"),
  coffee: c("#CBCB41"),
  coffeescript: c("#CBCB41"),
  cpp: c("#519ABA"),
  cxx: c("#519ABA"),
  cc: c("#F34B7D"),
  "c++": c("#F34B7D"),
  cs: c("#596706"),
  csharp: c("#596706"),
  css: c("#663399"),
  d: c("#B03931"),
  dart: c("#03589C"),
  dockerfile: c("#458EE6"),
  ex: c("#A074C4"),
  exs: c("#A074C4"),
  elixir: c("#A074C4"),
  erl: c("#B83998"),
  erlang: c("#B83998"),
  hrl: c("#B83998"),
  fs: c("#519ABA"),
  fsi: c("#519ABA"),
  fsx: c("#519ABA"),
  fsscript: c("#519ABA"),
  fsharp: c("#519ABA"),
  gleam: c("#FFAFF3"),
  go: c("#00ADD8"),
  groovy: c("#4A687C"),
  gradle: c("#005F87"),
  hbs: c("#F0772B"),
  handlebars: c("#F0772B"),
  hs: c("#A074C4"),
  haskell: c("#A074C4"),
  lhs: c("#A074C4"),
  htm: c("#E34C26"),
  html: c("#E44D26"),
  ini: c("#6D8086"),
  java: c("#CC3E44"),
  jar: c("#FFAF67"),
  js: c("#CBCB41"),
  javascript: c("#CBCB41"),
  kt: c("#7F52FF"),
  kts: c("#7F52FF"),
  kotlin: c("#7F52FF"),
  json: c("#CBCB41"),
  json5: c("#CBCB41"),
  jsonc: c("#CBCB41"),
  less: c("#563D7C"),
  lua: c("#51A0CF"),
  luau: c("#00A2FF"),
  md: c("#DDDDDD"),
  markdown: c("#DDDDDD"),
  mdx: c("#519ABA"),
  m: c("#599EFF"),
  mm: c("#519ABA"),
  ml: c("#E37933"),
  mli: c("#E37933"),
  ocaml: c("#E37933"),
  pas: c("#E3F171"),
  pascal: c("#E3F171"),
  pl: c("#519ABA"),
  pm: c("#519ABA"),
  perl: c("#519ABA"),
  php: c("#A074C4"),
  ps1: c("#4273CA"),
  psm1: c("#6975C4"),
  psd1: c("#6975C4"),
  powershell: c("#4273CA"),
  py: c("#FFBC03"),
  pyc: c("#FFE291"),
  pyd: c("#FFE291"),
  pyi: c("#FFBC03"),
  pyo: c("#FFE291"),
  python: c("#FFBC03"),
  r: c("#2266BA"),
  rake: c("#701516"),
  rakefile: c("#701516"),
  rb: c("#701516"),
  ruby: c("#701516"),
  gemspec: c("#701516"),
  ru: c("#701516"),
  erb: c("#701516"),
  rs: c("#DEA584"),
  rust: c("#DEA584"),
  rlib: c("#DEA584"),
  sass: c("#F55385"),
  scss: c("#F55385"),
  scala: c("#CC3E44"),
  sc: c("#CC3E44"),
  sh: c("#4D5A5E"),
  bash: c("#89E051"),
  zsh: c("#4D5A5E"),
  ksh: c("#4D5A5E"),
  fish: c("#4D5A5E"),
  shellscript: c("#4D5A5E"),
  sql: c("#DAD8D8"),
  sqlite: c("#DAD8D8"),
  sqlite3: c("#DAD8D8"),
  swift: c("#E37933"),
  svelte: c("#FF3E00"),
  svx: c("#FF0042"),
  tf: c("#5F43E9"),
  terraform: c("#5F43E9"),
  tfvars: c("#5F43E9"),
  toml: c("#9C4221"),
  ts: c("#519ABA"),
  typescript: c("#519ABA"),
  mts: c("#519ABA"),
  cts: c("#519ABA"),
  tsx: c("#20C2E3"),
  typst: c("#239DAE"),
  typ: c("#239DAE"),
  vue: c("#42B883"),
  xml: c("#FF6600"),
  xsl: c("#EB8C00"),
  yaml: c("#CB3434"),
  yml: c("#CB3434"),
  zig: c("#F7A41D"),
  zon: c("#F69A1B"),
  jsx: c("#20C2E3"),
  javascriptreact: c("#20C2E3"),
  typescriptreact: c("#20C2E3"),
  objectivec: c("#599EFF"),
  objectivecpp: c("#519ABA"),
  julia: c("#A270BA"),
  jl: c("#A270BA"),
  diff: c("#41535B"),
  patch: c("#41535B"),
  tex: c("#3D6117"),
  latex: c("#3D6117"),
  nix: c("#7EBAE4"),
  hcl: c("#844FBA"),
  astro: c("#E23F67"),
  prisma: c("#5A67D8"),
  graphql: c("#E535AB"),
  gql: c("#E535AB"),
  dockerignore: c("#458EE6"),
  ipynb: c("#F57D01"),
  npmignore: c("#E8274B"),
}

const tones = {
  astro: c("#E23F67"),
  biome: c("#E37933"),
  deno: c("#70FFAF"),
  dockerfile: c("#458EE6"),
  eslint: c("#4B32C3"),
  gopls: c("#00ADD8"),
  graphql: c("#E535AB"),
  html: c("#E44D26"),
  javascript: c("#CBCB41"),
  js: c("#CBCB41"),
  json: c("#CBCB41"),
  jsx: c("#20C2E3"),
  lua: c("#51A0CF"),
  markdown: c("#DDDDDD"),
  mdx: c("#519ABA"),
  node: c("#5FA04E"),
  nodejs: c("#5FA04E"),
  npm: c("#E8274B"),
  pnpm: c("#F9AD02"),
  bun: c("#EADCD1"),
  prisma: c("#5A67D8"),
  python: c("#FFBC03"),
  rust: c("#DEA584"),
  rustanalyzer: c("#DEA584"),
  sql: c("#DAD8D8"),
  stylelint: c("#F55385"),
  svelte: c("#FF3E00"),
  tailwindcss: c("#20C2E3"),
  terraform: c("#5F43E9"),
  typescript: c("#519ABA"),
  ts: c("#519ABA"),
  tsx: c("#20C2E3"),
  vue: c("#42B883"),
  vls: c("#42B883"),
  yaml: c("#CB3434"),
  yml: c("#CB3434"),
  c: c("#599EFF"),
  cpp: c("#519ABA"),
  csharp: c("#596706"),
  java: c("#CC3E44"),
  jdtls: c("#CC3E44"),
  kotlin: c("#7F52FF"),
  swift: c("#E37933"),
  sourcekit: c("#E37933"),
  dart: c("#03589C"),
  flutter: c("#03589C"),
  zig: c("#F7A41D"),
  zls: c("#F7A41D"),
  ruby: c("#701516"),
  solargraph: c("#701516"),
  php: c("#A074C4"),
  intelephense: c("#A074C4"),
  perl: c("#519ABA"),
  haskell: c("#A074C4"),
  hls: c("#A074C4"),
  elixir: c("#A074C4"),
  erlang: c("#B83998"),
  clojure: c("#8DC149"),
  ocaml: c("#E37933"),
  ocamllsp: c("#E37933"),
  fsharp: c("#519ABA"),
  fsac: c("#519ABA"),
  gleam: c("#FFAFF3"),
  shellscript: c("#4D5A5E"),
  bash: c("#89E051"),
  bashls: c("#89E051"),
  powershell: c("#4273CA"),
  pwsh: c("#4273CA"),
  nix: c("#7EBAE4"),
  nil: c("#7EBAE4"),
  typst: c("#239DAE"),
  tinymist: c("#239DAE"),
  latex: c("#3D6117"),
  texlab: c("#3D6117"),
  julia: c("#A270BA"),
  julials: c("#A270BA"),
  scala: c("#CC3E44"),
  metals: c("#CC3E44"),
  groovy: c("#4A687C"),
  handlebars: c("#F0772B"),
  diff: c("#41535B"),
  ini: c("#6D8086"),
  xml: c("#FF6600"),
  css: c("#663399"),
  sass: c("#F55385"),
  scss: c("#F55385"),
  less: c("#563D7C"),
  postcss: c("#563D7C"),
  objectivec: c("#599EFF"),
  objectivecpp: c("#519ABA"),
  clangd: c("#599EFF"),
  pascal: c("#E3F171"),
  jade: c("#E34C26"),
  pug: c("#E34C26"),
  terraformvars: c("#5F43E9"),
}

const serverTones = {
  typescript: c("#519ABA"),
  eslint: c("#4B32C3"),
  graphql: c("#E535AB"),
  stylelint: c("#F55385"),
  biome: c("#E37933"),
  gopls: c("#00ADD8"),
  rustanalyzer: c("#DEA584"),
  vls: c("#42B883"),
  jdtls: c("#CC3E44"),
  kotlin: c("#7F52FF"),
  sourcekit: c("#E37933"),
  dart: c("#03589C"),
  zls: c("#F7A41D"),
  solargraph: c("#701516"),
  intelephense: c("#A074C4"),
  hls: c("#A074C4"),
  elixirls: c("#A074C4"),
  erlangls: c("#B83998"),
  clojurelsp: c("#8DC149"),
  ocamllsp: c("#E37933"),
  fsac: c("#519ABA"),
  bashls: c("#89E051"),
  powershelleditor: c("#4273CA"),
  nil: c("#7EBAE4"),
  tinymist: c("#239DAE"),
  texlab: c("#3D6117"),
  julials: c("#A270BA"),
  metals: c("#CC3E44"),
  clangd: c("#599EFF"),
}

const defaults = {
  icon: "󰈙",
  folder: "󰉋",
  tone: c("#A6ADC8"),
}

function sourcekey(input?: string) {
  if (!input) return ""
  const key = input.toLowerCase().trim()
  return key.split(":")[0]?.trim() ?? key
}

function filekey(input?: string) {
  if (!input) return ""
  return input.toLowerCase().trim()
}

function pick<T>(map: Record<string, T>, key: string) {
  return map[key]
}

export function langicon(input?: string) {
  if (!input) return defaults.icon
  const key = filekey(input)
  const ext = path.extname(key).slice(1)
  return pick(files, key) ?? pick(langs, key) ?? pick(exts, key) ?? pick(exts, ext) ?? defaults.icon
}

export function langcolor(input?: string) {
  if (!input) return defaults.tone
  const key = filekey(input)
  const ext = path.extname(key).slice(1)
  return pick(fileTones, key) ?? pick(tones, key) ?? pick(extTones, key) ?? pick(extTones, ext) ?? defaults.tone
}

export function lspicon(input?: string) {
  if (!input) return defaults.icon
  const key = sourcekey(input)
  return pick(servers, key) ?? pick(langs, key) ?? defaults.icon
}

export function lspcolor(input?: string) {
  if (!input) return defaults.tone
  const key = sourcekey(input)
  return pick(serverTones, key) ?? pick(tones, key) ?? defaults.tone
}

export function pathicon(input?: string) {
  if (!input) return defaults.folder
  const base = path.basename(input).toLowerCase()
  if (base === "." || !path.extname(base)) return defaults.folder
  return langicon(base)
}

export function pathlabel(input?: string) {
  if (!input) return pathicon(input)
  return `${pathicon(input)} ${input}`
}
